version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pc_builder_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pc_builder_db
      MYSQL_USER: pcbuilder
      MYSQL_PASSWORD: pcbuilder123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
