# Generated by Django 6.0.3 on 2026-03-31 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buget_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jocuri_pref', models.JSONField(blank=True, default=list)),
                ('locatie', models.CharField(default='Romania', max_length=100)),
                ('rezolutie_dorita', models.CharField(choices=[('1080p', 'Full HD (1080p)'), ('1440p', 'Quad HD (1440p)'), ('4K', 'Ultra HD (4k)')], default='1080p', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
