# Generated by Django 6.0.3 on 2026-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpu_preferat',
            field=models.CharField(choices=[('Oricare', 'Cel mai ieftin (Default)'), ('AMD', 'AMD'), ('Intel', 'Intel')], default='Oricare', max_length=20, verbose_name='Procesor (CPU) Preferat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gpu_preferat',
            field=models.CharField(choices=[('Oricare', 'Cea mai ieftină / Best Value (Default)'), ('NVIDIA', 'NVIDIA (GeForce RTX / GTX)'), ('AMD', 'AMD (Radeon RX)'), ('Intel', 'Intel (ARC)')], default='Oricare', max_length=20, verbose_name='Cip Grafic (GPU) Preferat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psu_preferat',
            field=models.CharField(choices=[('Oricare', 'Cel mai ieftin (Default)'), ('Branduri Recomandate', [('Seasonic', 'Seasonic'), ('Corsair', 'Corsair'), ('be quiet!', 'be quiet!'), ('ASUS', 'ASUS'), ('MSI', 'MSI')]), ('Alte Branduri', [('EVGA', 'EVGA'), ('FSP', 'FSP (Fortron)'), ('Gigabyte', 'Gigabyte'), ('Thermaltake', 'Thermaltake'), ('Deepcool', 'Deepcool')])], default='Oricare', max_length=50, verbose_name='Sursă (PSU) Preferată'),
        ),
    ]
