# Generated by Django 6.0.3 on 2026-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_accessory_externalstorage_fan_monitor_networkadapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='inaltime_max_cooler_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lungime_max_gpu_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='suport_radiator_mm',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cpu',
            name='threaduri',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='tip_vram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='nr_sloturi_m2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sloturi_ram',
            field=models.IntegerField(default=4),
        ),
    ]
