# Generated by Django 6.0.3 on 2026-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_accessory_magazin_alter_accessory_pret_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='ExternalStorage',
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
        migrations.DeleteModel(
            name='OpticalDrive',
        ),
        migrations.DeleteModel(
            name='SoundCard',
        ),
        migrations.DeleteModel(
            name='UPS',
        ),
        migrations.AddField(
            model_name='case',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='networkadapter',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
