# Generated by Django 6.0.3 on 2026-04-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_delete_accessory_delete_externalstorage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='capacitate_max_ram_gb',
            field=models.IntegerField(default=0),
        ),
    ]
