# Generated by Django 6.0.3 on 2026-04-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_motherboard_capacitate_max_ram_gb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='este_modulara',
            field=models.CharField(default='Non', max_length=10),
        ),
    ]
