# Generated by Django 6.0.3 on 2026-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_alter_psu_este_modulara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nume', models.CharField(max_length=300)),
            ],
        ),
    ]
