# Generated by Django 6.0.3 on 2026-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='chipset_brand',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
