# Generated by Django 6.0.3 on 2026-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_gpu_chipset_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='capacitate_modul_gb',
            field=models.IntegerField(default=0),
        ),
    ]
