# Generated by Django 6.0.3 on 2026-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_ram_capacitate_modul_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu',
            name='format',
            field=models.CharField(default='ATX', max_length=50),
        ),
    ]
